//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_MQTTClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Analog_1
    {
        public int Id { get; set; }
        public Nullable<float> Raw_valvue { get; set; }
        public Nullable<float> Process_value { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
    }
}
