//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_MQTTClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data_Analog_test
    {
        public int myID { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<double> RawValue { get; set; }
        public Nullable<double> ProcessValue { get; set; }
    }
}
