//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AS_MQTTClient.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modbus_slave_MFM383A
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<float> I_Avg { get; set; }
        public Nullable<float> P_Sum { get; set; }
        public Nullable<float> Q_Sum { get; set; }
        public Nullable<float> S_Sum { get; set; }
        public Nullable<float> Energy_Total { get; set; }
    }
}
